import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const backend = new URL('../../OBBIAN_BACKEND/', import.meta.url);
const { createService } = await import(new URL('src/service.js', backend));
const db = JSON.parse(await readFile(new URL('data/seed.json', backend), 'utf8'));
let queue = Promise.resolve();
const service = createService({read: () => structuredClone(db), update: fn => {const operation = queue.then(() => fn(db)); queue = operation.catch(() => {}); return operation;}});
const date = service.config().defaultDate;
const car = db.vehicles.find(v => v.available);
const params = { date, lat: car.lat, lng: car.lng, radius: 100, budget: 100000, category: car.category, transmission: car.transmission };
const results = service.search(params).results;
assert(results.some(v => v.id === car.id));
assert(results.every(v => v.category === car.category && v.transmission === car.transmission));
assert.equal(results.find(v => v.id === car.id).distanceMeters, 0);
assert.equal(service.search({...params, category: 'does-not-exist'}).count, 0);
assert.throws(() => service.search({...params, lat: 200}));
assert.throws(() => service.search({...params, radius: -1}));
const input = {vehicleId: car.id, date, termsAccepted:true, paymentMethod:db.config.paymentMethods[0].value, name:'Test User', mobile:'9876543210', licence:'DL-TEST1234'};
const booked = await Promise.allSettled([service.createBooking('test', input, 'test-request-1'), service.createBooking('test2', input, 'test-request-2')]);
assert.equal(booked.filter(r => r.status === 'fulfilled').length, 1);
assert.equal(booked.find(r => r.status === 'rejected').reason.status, 409);
assert.equal(service.search(params).results.some(v => v.id === car.id), false);
console.log('PASS: coordinate validation, category/transmission, distance, availability, concurrent reservation checks');
