import {test,expect} from '@playwright/test';
test('search, booking, persistence, modification and cancellation',async({page})=>{
 await page.goto('/');
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await expect(page.getByRole('heading',{name:'3 vehicles match your search'})).toBeVisible();
 await page.getByRole('button',{name:'View details',exact:true}).click();
 await page.getByRole('link',{name:'Reserve vehicle →'}).click();
 await page.getByLabel('Mobile number').fill('9876543210');
 await page.getByLabel('Driving licence').fill('DL-DEMO-123456');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Confirm reservation'}).click();
 await expect(page.getByRole('heading',{name:'Reservation confirmed',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'View My Trips'}).click();
 await expect(page.getByRole('tab',{name:'Upcoming 2'})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('tab',{name:'Upcoming 2'})).toBeVisible();
 await page.getByRole('button',{name:'Manage booking'}).first().click();
 await page.getByLabel('New pickup date').fill('2028-12-20');
 await page.getByRole('button',{name:'Save changes'}).click();
 await expect(page.getByText('20 Dec 2028 · 10:00 AM – 8:00 PM')).toBeVisible();
 await page.getByRole('button',{name:'Manage booking'}).first().click();
 await page.getByRole('button',{name:'Cancel reservation'}).click();
 await page.getByRole('tab',{name:'Cancelled 1'}).click();
 await expect(page.getByRole('button',{name:'Download receipt'})).toBeVisible();
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Download receipt'}).click();
 expect((await download).suggestedFilename()).toMatch(/receipt.txt$/);
});
test('filters, saved vehicles, policy and help interactions',async({page})=>{
 await page.goto('/');
 await page.getByRole('combobox', {name: 'Daily budget'}).click();
 await page.getByRole('option', {name: 'Under ₹2,000/day'}).click();
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await expect(page.getByRole('heading',{name:'No rides found'})).toBeVisible();
 await page.getByRole('link',{name:'Saved',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toBeVisible();
 await page.getByRole('button',{name:'Remove',exact:true}).first().click();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toHaveCount(0);
 await page.reload();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toHaveCount(0);
 await page.goto('/policy');
 await page.getByRole('button',{name:'Insurance coverage',exact:true}).click();
 await expect(page.getByRole('log').getByText(/₹249 demo insurance/)).toBeVisible();
 await page.getByLabel('Ask another policy question').fill('What is the weather?');
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(page.getByText(/I don’t have a matching answer/)).toBeVisible();
 await page.getByRole('link',{name:'Support',exact:true}).click();
 await page.getByLabel('Search help articles').fill('deposit');
 await page.getByRole('button',{name:'Security deposit timeline'}).click();
 await expect(page.getByText(/5–7 business days/)).toBeVisible();
 await page.getByRole('button',{name:'Contact options'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('all screens render without horizontal overflow or runtime errors',async({page})=>{
 const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
 for(const route of ['/','/search','/vehicle','/checkout','/confirmation','/tracking','/policy','/trips','/saved','/support']) {
  await page.goto(route); await expect(page.locator('h1')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 }
 expect(errors).toEqual([]);
 await page.screenshot({path:`test-results/${test.info().project.name}-support.png`,fullPage:true});
 await page.goto('/');await expect(page.locator('h1')).toBeVisible();
 await page.screenshot({path:`test-results/${test.info().project.name}-discover.png`,fullPage:true});
});
test('tracking can be paused and resumed',async({page})=>{
 await page.goto('/tracking');
 await page.getByRole('button',{name:'Pause tracking'}).click();
 await expect(page.getByText('● PAUSED')).toBeVisible();
 await page.getByRole('button',{name:'Resume tracking'}).click();
 await expect(page.getByText('● LIVE · Updating now')).toBeVisible();
});
test('selected vehicle and support handoff survive navigation',async({page})=>{
 await page.goto('/search');
 await page.getByRole('button',{name:'Select',exact:true}).first().click();
 await expect(page.getByRole('heading',{name:'Kia Seltos'})).toBeVisible();
 await page.getByRole('link',{name:'Reserve vehicle →'}).click();
 await expect(page.getByRole('heading',{name:'Kia Seltos'})).toBeVisible();
 await expect(page.getByText('₹3,099', {exact:true})).toBeVisible();
 await page.goto('/policy');
 await page.getByRole('button',{name:'Talk to a human'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByLabel('Email', {exact:true}).fill('demo@example.com');
 await page.getByLabel('How can we help?').fill('Please help me change my pickup location.');
 await page.getByRole('button',{name:'Submit demo request'}).click();
 await expect(page.getByRole('status')).toContainText('no message was sent');
});
test('custom dropdown supports keyboard, dismissal, sorting and form values', async ({page}) => {
 await page.goto('/');
 const radius = page.getByRole('combobox', {name: 'Search radius'});
 await radius.focus();
 await radius.press('ArrowDown');
 await expect(radius).toHaveAttribute('aria-expanded', 'true');
 await radius.press('ArrowDown');
 await radius.press('Enter');
 await expect(radius).toContainText('3 km radius');
 await expect(radius).toBeFocused();
 await radius.click();
 await radius.press('End');
 await radius.press('Escape');
 await expect(radius).toHaveAttribute('aria-expanded', 'false');
 await expect(radius).toContainText('3 km radius');
 await radius.click();
 await page.getByRole('heading', {name: 'Find your perfect ride'}).click();
 await expect(radius).toHaveAttribute('aria-expanded', 'false');
 await page.getByRole('link', {name: 'Search vehicles →'}).click();
 await expect(page.getByRole('heading', {name: '1 vehicles match your search'})).toBeVisible();
 await page.goto('/search');
 const sort = page.getByRole('combobox', {name: 'Sort vehicles'});
 await sort.focus();
 await sort.press('p');
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
 await sort.press('Enter');
 await expect(sort).toContainText('Price: low to high');
 await expect(page.locator('section h2').first()).toHaveText('Tata Nexon');
 await page.goto('/checkout');
 const payment = page.getByRole('combobox', {name: 'Payment method'});
 await payment.click();
 await page.getByRole('option', {name: 'Demo UPI'}).click();
 await expect(payment).toContainText('Demo UPI');
 await expect(payment).toHaveAttribute('aria-expanded', 'false');
 expect(await page.locator('form').evaluate(form => new FormData(form as HTMLFormElement).get('payment'))).toBe('upi');
});
