import {test,expect} from '@playwright/test';
test('search, booking, persistence, modification and cancellation',async({page})=>{
 await page.goto('/');
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await expect(page.getByRole('heading',{name:'3 vehicles match your search'})).toBeVisible();
 await page.getByRole('button',{name:'View details',exact:true}).click();
 await page.getByRole('link',{name:'Reserve vehicle →'}).click();
 await page.getByLabel('Mobile number').fill('9876543210');
 await page.getByLabel('Driving licence').fill('DL-DEMO-123456');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Confirm reservation'}).click();
 await expect(page.getByRole('heading',{name:'Reservation confirmed',exact:true})).toBeVisible();
 await page.getByRole('link',{name:'View My Trips'}).click();
 await expect(page.getByRole('tab',{name:'Upcoming 1'})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('tab',{name:'Upcoming 1'})).toBeVisible();
 await page.getByRole('button',{name:'Manage booking'}).first().click();
 await page.getByLabel('New pickup date').fill('2028-12-20');
 await page.getByRole('button',{name:'Save changes'}).click();
 await expect(page.getByText('20 Dec 2028 · 10:00 AM – 8:00 PM')).toBeVisible();
 await page.getByRole('button',{name:'Manage booking'}).first().click();
 await page.getByRole('button',{name:'Cancel reservation'}).click();
 await page.getByRole('tab',{name:'Cancelled 1'}).click();
 await expect(page.getByRole('button',{name:'Download receipt'})).toBeVisible();
 const download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Download receipt'}).click();
 expect((await download).suggestedFilename()).toMatch(/receipt.txt$/);
});
test('filters, saved vehicles, policy and help interactions',async({page})=>{
 await page.goto('/');
 await page.getByRole('combobox', {name: 'Daily budget'}).click();
 await page.getByRole('option', {name: 'Under ₹2,000/day'}).click();
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await expect(page.getByRole('heading',{name:'No rides found'})).toBeVisible();
 await page.getByRole('link',{name:'← Edit search'}).click();
 await page.getByRole('combobox', {name: 'Daily budget'}).click();
 await page.getByRole('option', {name: 'Under ₹3,000/day'}).click();
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await page.getByRole('button',{name:'Save Hyundai Creta'}).click();
 await page.getByRole('link',{name:'Saved',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Saved vehicles'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toBeVisible();
 await page.reload();
 await expect(page.getByRole('heading',{name:'Saved vehicles'})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toBeVisible();
 await page.getByRole('button',{name:'Remove',exact:true}).first().click();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toHaveCount(0);
 await page.reload();
 await expect(page.getByRole('heading',{name:'Hyundai Creta'})).toHaveCount(0);
 await page.goto('/policy');
 await page.getByRole('button',{name:'Insurance coverage',exact:true}).click();
 await expect(page.getByRole('log').getByText(/₹249 demo insurance/)).toBeVisible();
 await page.getByLabel('Ask another policy question').fill('What is the weather?');
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect(page.getByText(/I don’t have a matching answer/)).toBeVisible();
 await page.getByRole('link',{name:'Support',exact:true}).click();
 await page.getByLabel('Search help articles').fill('deposit');
 await page.getByRole('button',{name:'Security deposit timeline'}).click();
 await expect(page.getByText(/5–7 business days/)).toBeVisible();
 await page.getByRole('button',{name:'Contact options'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByRole('button',{name:'Close dialog'}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('all screens render without horizontal overflow or runtime errors',async({page})=>{
 const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
 for(const route of ['/','/search','/vehicle','/checkout','/confirmation','/tracking','/policy','/trips','/saved','/support']) {
  await page.goto(route); await expect(page.locator('h1')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 }
 expect(errors).toEqual([]);
 await page.screenshot({path:`test-results/${test.info().project.name}-support.png`,fullPage:true});
 await page.goto('/');await expect(page.locator('h1')).toBeVisible();
 await page.screenshot({path:`test-results/${test.info().project.name}-discover.png`,fullPage:true});
});
test('tracking reflects live backend status for the active booking',async({page})=>{
 await page.goto('/');
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await page.getByRole('button',{name:'View details',exact:true}).click();
 await page.getByRole('link',{name:'Reserve vehicle →'}).click();
 await page.getByLabel('Mobile number').fill('9876543210');
 await page.getByLabel('Driving licence').fill('DL-DEMO-123456');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Confirm reservation'}).click();
 await page.getByRole('link',{name:'Track vehicle live →'}).click();
 await expect(page.getByText('Driver en route').first()).toBeVisible();
 await page.getByRole('link',{name:'My Trips',exact:true}).click();
 await page.getByRole('button',{name:'Manage booking'}).first().click();
 await page.getByRole('button',{name:'Cancel reservation'}).click();
});
test('selected vehicle and support handoff survive navigation',async({page})=>{
 await page.goto('/search');
 await page.getByRole('button',{name:'Select',exact:true}).first().click();
 await expect(page.getByRole('heading',{name:'Kia Seltos'})).toBeVisible();
 await page.getByRole('link',{name:'Reserve vehicle →'}).click();
 await expect(page.getByRole('heading',{name:'Kia Seltos'})).toBeVisible();
 await expect(page.getByText('₹3,099', {exact:true})).toBeVisible();
 await page.goto('/policy');
 await page.getByRole('button',{name:'Talk to a human'}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByLabel('Email', {exact:true}).fill('demo@example.com');
 await page.getByLabel('How can we help?').fill('Please help me change my pickup location.');
 await page.getByRole('button',{name:'Submit request'}).click();
 await expect(page.getByRole('status')).toContainText('Support request submitted');
});
test('geospatial map shows nearby vehicles and supports picking a search location', async ({page}) => {
 await page.goto('/');
 await expect(page.locator('.leaflet-container')).toBeVisible();
 await expect(page.getByText(/\d+ nearby/)).toBeVisible();
 const locateButton = page.getByRole('button', {name: /Use my location/});
 await expect(locateButton).toBeVisible();
 await page.locator('.leaflet-container').click({position: {x: 60, y: 60}});
 await expect(page.getByRole('button', {name: 'Using your location'})).toBeVisible();
 await expect(page.getByText('Tap the map to search a different spot')).toBeVisible();
});
test('an active trip can be completed by the renter and moves to the Completed tab', async ({page}) => {
 test.setTimeout(60000);
 await page.goto('/');
 await page.getByRole('link',{name:'Search vehicles →'}).click();
 await page.getByRole('button',{name:'View details',exact:true}).click();
 await page.getByRole('link',{name:'Reserve vehicle →'}).click();
 await page.getByLabel('Mobile number').fill('9876543210');
 await page.getByLabel('Driving licence').fill('DL-DEMO-123456');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Confirm reservation'}).click();
 await page.getByRole('link',{name:'Track vehicle live →'}).click();
 await expect(page.getByText('Driver en route').first()).toBeVisible();
 await expect(page.getByText('Vehicle arrived').first()).toBeVisible({timeout: 40000});
 await expect(page.getByRole('button', {name: 'Complete trip'})).toBeVisible({timeout: 10000});
 await page.getByRole('button', {name: 'Complete trip'}).click();
 await expect(page.getByRole('tab', {name: 'Upcoming 0'})).toBeVisible();
 await page.getByRole('tab', {name: 'Completed 1'}).click();
 await expect(page.getByRole('button', {name: 'Download receipt'})).toBeVisible();
});
test('custom dropdown supports keyboard, dismissal, sorting and form values', async ({page}) => {
 await page.goto('/');
 const radius = page.getByRole('combobox', {name: 'Search radius'});
 await radius.focus();
 await radius.press('ArrowDown');
 await expect(radius).toHaveAttribute('aria-expanded', 'true');
 await radius.press('ArrowDown');
 await radius.press('Enter');
 await expect(radius).toContainText('3 km radius');
 await expect(radius).toBeFocused();
 await radius.click();
 await radius.press('End');
 await radius.press('Escape');
 await expect(radius).toHaveAttribute('aria-expanded', 'false');
 await expect(radius).toContainText('3 km radius');
 await radius.click();
 await page.getByRole('heading', {name: 'Find your perfect ride'}).click();
 await expect(radius).toHaveAttribute('aria-expanded', 'false');
 await page.getByRole('link', {name: 'Search vehicles →'}).click();
 await expect(page.getByRole('heading', {name: '1 vehicles match your search'})).toBeVisible();
 await page.goto('/search');
 const sort = page.getByRole('combobox', {name: 'Sort vehicles'});
 await sort.focus();
 await sort.press('p');
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
 await sort.press('Enter');
 await expect(sort).toContainText('Price: low to high');
 await expect(page.locator('section h2').first()).toHaveText('Tata Nexon');
 await page.goto('/checkout');
 const payment = page.getByRole('combobox', {name: 'Payment method'});
 await expect(payment).toContainText('Pay at pickup');
 expect(await page.locator('form').evaluate(form => new FormData(form as HTMLFormElement).get('paymentMethod'))).toBe('pickup');
});
